services:
  # Service name, container name will be <project name>-<service name>-1 by default
  barman:
    # Docker image that it will set up
    image: "${APP_IMAGE}:${VERSION}"
    # A volume is basically a file system shared between the host and the container
    # It will wait forever for 'anything' to appear. This prevents it from stopping.
    tty: true
    volumes:
      # <volume name in volumes below>:<container destination directory>
      # This means the volume will be accessible from the container in the dest. directory in the container
      - barman_volume:${RESOURCES_TARGET}
    # Environment file to load into the container
    # env_file:
    #   - .env.barman
    #   - .env.deploy
    # Some environment variables depend on deployment variables, so we load those in manually
    environment:
      PGDATA: ${RESOURCES_TARGET}
    # This maps ports, so the container port will be available at localhost:<HOST_PORT>
    # ports:
    #  - "127.0.0.1:${HOST_PORT}:${CONTAINER_PORT}"
volumes:
  # This name should correspond to the volume mentioned in volumes above
  barman_volume:
    # A local directory
    driver: local
    driver_opts:
      o: bind
      type: none
      # The directory in the host directory that will be loaded as the source for the volume
      device: ${RESOURCES_SOURCE}
networks:
  # Set up a network so that other containers on this network can access each other
  # A different container on this network can access this container by using the container name as the hostname
  # So localhost:3000 is exposed to other containers as <container name>:3000
  default:
    external: true
    name: dodeka
