APISERVER_ENV="localdev"

DB_USER="dodeka"
DB_PASS="postpost"
DB_HOST="localhost"
DB_PORT=3141
DB_NAME="dodeka"
DB_NAME_ADMIN="postgres"

KV_HOST="localhost"
KV_PORT=6379
KV_PASS="redisredis"

MAIL_ENABLED=false
KEY_PASS="AT_av0v62Z3hQH50VYwKBks1-VSukK9xDN_Ur34mdZ4"
MAIL_PASS=""

SMTP_SERVER = "abcmail"
SMTP_PORT = 587